version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"