eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  username: ${EUREKA_USERNAME:username}
  password: ${EUREKA_PASSWORD:password}
server:
  port: 8761
management:
  tracing:
    sampling:
      probability: 1.0