spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5000/order-service
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://username:password@localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0